# Generated by Django 4.1.2 on 2022-12-07 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favourites',
        ),
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
