# Generated by Django 4.1.2 on 2022-12-21 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_favourites_book_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
