# Generated by Django 4.1.2 on 2022-12-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_recommendations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendations',
        ),
    ]
